# Generated by Django 3.2 on 2022-12-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='type',
            field=models.TextField(choices=[('MV', 'Movie'), ('NM', 'Not_movie')], verbose_name='type'),
        ),
    ]
